config/routes.rb
Rails.application.routes.draw do

  resources :players, except: [:show]

  root to: "players#index"

  get 'players/index'

  get 'players/new'

  get 'players/create'

  get 'players/edit'

  get 'players/update'

  get 'players/destroy'

end

app/models/player.rb
class Player
  include Mongoid::Document
  field :first_name, type: String
  field :last_name, type: String
  field :age, type: String
  field :position, type: String
  field :team, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to players_path, notice: "The player has been created!" and return
    end

    render 'new'
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])

    if @player.update_attributes(player_params)
      redirect_to players_path, notice: "#{@player.first_name} #{@player.last_name} has been updated!" and return
    end

    render 'edit'
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    redirect_to players_path, notice: "#{@player.first_name} #{@player.last_name} has been deleted!" and return
  end

private
  def player_params
    params.require(:player).permit(:first_name, :last_name, :age, :position, :team)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Players</title>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/players/_form.html.erb
<%= form_for @player do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :age %>
    <%= f.text_field :age, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :position %>
    <%= f.text_field :position, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :team %>
    <%= f.text_field :team, class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/players/create.html.erb
<h1>Players#create</h1>
<p>Find me in app/views/players/create.html.erb</p>

app/views/players/destroy.html.erb
<h1>Players#destroy</h1>
<p>Find me in app/views/players/destroy.html.erb</p>

app/views/players/edit.html.erb
<h1>Editar jugador</h1>
<div class="well">
  <%= render "form" %>
</div>

app/views/players/index.html.erb
<h1>Jugadores</h1>
<div class="well">
  <%= link_to "Nuevo jugador", new_player_path, class: "btn btn-primary" %>
</div>

<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>
        Nombre
      </th>
      <th>
        Apellido
      </th>
      <th>
        Edad
      </th>
      <th>
        Posición
      </th>
      <th>
        Equipo
      </th>
      <th>
        Acción1
      </th>
      <th>
        Acción2
      </th>
    </tr>
  </thead>
  <tbody>
    <% if @players.size == 0 %>
      <tr>
        <td colspan="7">No hay jugadores en la tabla</td>
      </tr>
    <% else %>
      <% @players.each do |player| %>
        <tr>
          <td>
            <%= player.first_name %>
          </td>
          <td>
            <%= player.last_name %>
          </td>
          <td>
            <%= player.age %>
          </td>
          <td>
            <%= player.position %>
          </td>
          <td>
            <%= player.team %>
          </td>
          <td>
            <%= link_to "Edit", edit_player_path(player), class: "btn btn-default" %>
          </td>
          <td>
            <%= button_to "Delete", player, method: :delete, data: {confirm: "Are your sure you wish to delete #{player.first_name} #{player.last_name}?"}, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/players/new.html.erb
<h1>Nuevo jugador</h1>
<div class="well">
  <%= render "form" %>
</div>

app/views/players/update.html.erb
<h1>Players#update</h1>
<p>Find me in app/views/players/update.html.erb</p>